### ISSUE TITLE
plugin tests failing with SNAPSHOT builds using Bundler 2.3.9

### ISSUE THREAD

**Issue by kares** [elastic/logstash#13890]
sample 7.x :red_circle: https://app.travis-ci.com/github/logstash-plugins/logstash-input-tcp/jobs/563182748
sample 8.x :red_circle: https://app.travis-ci.com/github/logstash-plugins/logstash-input-elasticsearch/jobs/563200407

```
Bundle complete! 124 Gemfile dependencies, 236 gems now installed.

Bundled gems are installed into `/usr/share/logstash/vendor/bundle`

--- ERROR REPORT TEMPLATE -------------------------------------------------------

NoMethodError: undefined method `metadata' for nil:NilClass

  /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.3.9/lib/bundler/cli/common.rb:22:in `block in output_fund_metadata_summary'

  org/jruby/RubyArray.java:3250:in `count'

  /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.3.9/lib/bundler/cli/common.rb:22:in `output_fund_metadata_summary'

  /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.3.9/lib/bundler/cli/install.rb:87:in `run'

  /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.3.9/lib/bundler/cli.rb:255:in `block in install'

  /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.3.9/lib/bundler/settings.rb:131:in `temporary'

  /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.3.9/lib/bundler/cli.rb:254:in `install'

  /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'

  /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'

  /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'

  /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.3.9/lib/bundler/cli.rb:31:in `dispatch'

  /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'

  /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.3.9/lib/bundler/cli.rb:25:in `start'

  /usr/share/logstash/bin/bundle:18:in `block in /usr/share/logstash/bin/bundle'

  /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.3.9/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'

  /usr/share/logstash/bin/bundle:17:in `<main>'


## Environment

Bundler       2.3.9

  Platforms   ruby, universal-java-11

Ruby          2.5.8p0 (2021-11-30 revision 67882) [universal-java-11]

  Full Path   /usr/share/logstash/vendor/jruby/bin/jruby

  Config Dir  /usr/share/logstash/vendor/jruby/etc

RubyGems      3.1.6

  Gem Home    /usr/share/logstash/vendor/bundle/jruby/2.5.0

  Gem Path    /usr/share/logstash/vendor/bundle/jruby/2.5.0

  User Home   /usr/share/logstash

  User Path   /usr/share/logstash/.gem/jruby/2.5.0

  Bin Dir     /usr/share/logstash/vendor/bundle/jruby/2.5.0/bin

OpenSSL       

  Compiled    JRuby-OpenSSL 0.11.0

  Loaded      JRuby-OpenSSL 0.11.0

  Cert File   /usr/share/logstash/jdk/lib/security/cacerts

  Cert Dir    /etc/ssl/certs

Tools         

  Git         not installed

  RVM         not installed

  rbenv       not installed

  chruby      not installed


## Bundler Build Metadata

Built At          2022-03-09

Git SHA           7f90c0083a

Released Version  true


## Bundler settings

bin_path

  Set via BUNDLE_BIN_PATH: "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.3.9/exe/bundle"

gemfile

  Set via BUNDLE_GEMFILE: "/usr/share/logstash/Gemfile"

with

  Set for your local app (/usr/share/logstash/.bundle/config): [:test, :ci]

```

**Comment by kares** [comment]
pinning Bundler to `< 2.3.9` might resolve the issue, we could wait for a few days to see if 2.3.10 is pushed ...

**Comment by kares** [comment]
been resolved on LS side
