### ISSUE TITLE
undefined local variable or method `type'

### ISSUE THREAD

**Issue by matejzero** [elastic/logstash#3261]
Hello!

Today I upgraded my logstash from 1.4.2 to the latest 1.5.0 GA and I'm having troubles starting it. When I start Logstash, it starts but then throws NameError:
```
/opt/logstash/bin/logstash -f /etc/logstash/conf.d/
courier plugin is using the 'milestone' method to declare the version of the plugin this method is deprecated in favor of declaring the version inside the gemspec. {:level=>:warn}
courier plugin doesn't have a version. This plugin isn't well
 supported by the community and likely has no maintainer. {:level=>:warn}
Logstash startup completed {"plugin"=>"input/courier", "port"=>5043}
NameError: undefined local variable or method `type' for #<LogStash::Pipeline:0x3603bd21>
    output_func at (eval):4061
   outputworker at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:244
  start_outputs at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:166
```

I started Logstash with --debug, but the last lines aren't really useful:
```
Date parsing done {:value=>1431949540.731, :level=>:debug, :file=>"logstash/filters/date.rb", :line=>"220", :method=>"filter", "plugin"=>"input/courier", "port"=>5043}
filters/LogStash::Filters::Mutate: adding tag {:tag=>"parsed", :level=>:debug, :file=>"logstash/filters/base.rb", :line=>"207", :method=>"filter_matched", "plugin"=>"input/courier", "port"=>5043}
filters/LogStash::Filters::Mutate: adding tag {:tag=>"amavis-filter", :level=>:debug, :file=>"logstash/filters/base.rb", :line=>"207", :method=>"filter_matched", "plugin"=>"input/courier", "port"=>5043}
filters/LogStash::Filters::Mutate: adding value to field {:field=>"logstash_node", :value=>["logstash1"], :level=>:debug, :file=>"logstash/filters/base.rb", :line=>"193", :method=>"filter_matched", "plugin"=>"input/courier", "port"=>5043}
NameError: undefined local variable or method `type' for #<LogStash::Pipeline:0x1683cc5c>
    output_func at (eval):4057
   outputworker at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:244
  start_outputs at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:166

```

What can be the reason?

**Comment by jsvd** [comment]
Can you provide your configuration file?

**Comment by matejzero** [comment]
I'm currently trying to add/remove config files to see, which one is causing troubles, since I have around 20 config files. Will report the one causing problems.

**Comment by matejzero** [comment]
I found my problem. I have some of my 'if' sentences in multiple lines and that seems like it doesn't work in 1.5.0 anymore:

My config file looked like this:
```
  ### Debug(untagged) to logstash.stdout
  if  ( [type] != "amavis" ) and 
      ( [type] != "apache" ) and 
      ( [type] != "dovecot" ) and 
      ( [type] != "roundcube" ) and 
      ( [type] != "postfix" ) and
      ( [type] != "simplesaml" ) and
      ( [type] != "cisco" ) {
    stdout { codec => rubydebug }
  }
```

I moved everything in one line and now it works.

Matej

**Comment by jsvd** [comment]
@matejzero you can also do: `if [type] not in ['a', 'b', 'c'] { }`

example: 

```
% bin/logstash -e "input { generator { count => 1 type => "hello" } } output { if [type] not in ['hi', 'ola', 'test',  'potatoes'] { stdout { codec => rubydebug} } }"
{
       "message" => "Hello world!",
      "@version" => "1",
    "@timestamp" => "2015-05-18T12:33:53.481Z",
          "type" => "hello",
          "host" => "Joaos-MBP-2.lan",
      "sequence" => 0
}
Logstash startup completed
Logstash shutdown completed
```

```
% bin/logstash -e "input { generator { count => 1 type => "test" } } output { if [type] not in ['hi', 'ola', 'test',  'potatoes'] { stdout { codec => rubydebug} } }"
Logstash startup completed
Logstash shutdown completed
```

**Comment by matejzero** [comment]
Now that's nicer. Will fix my configs.

Thanks!
