### ISSUE TITLE
Exception in filterworker {"exception"=>#<NameError: undefined local variable or method `event'

### ISSUE THREAD

**Issue by rmoff** [elastic/logstash#3125]
logstash 1.5.0-rc3 running under java version "1.8.0_45"

Config worked fine on logstash 1.5.0-rc1, now errors out: 

```Exception in filterworker {"exception"=>#<NameError: undefined local variable or method `event' for #<LogStash::Pipeline:0x5bf514af>>, "backtrace"=>["(eval):55:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/hdd/ELK/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc3-java/lib/logstash/pipeline.rb:309:in `flush_filters'", "org/jruby/RubyArray.java:1613:in `each'", "/hdd/ELK/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc3-java/lib/logstash/pipeline.rb:308:in `flush_filters'", "/hdd/ELK/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc3-java/lib/logstash/pipeline.rb:317:in `flush_filters_to_output!'", "/hdd/ELK/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc3-java/lib/logstash/pipeline.rb:223:in `filterworker'", "org/jruby/ext/thread/Mutex.java:149:in `synchronize'", "/hdd/ELK/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc3-java/lib/logstash/pipeline.rb:223:in `filterworker'", "/hdd/ELK/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc3-java/lib/logstash/pipeline.rb:156:in `start_filters'"], :level=>:error}```

Narrowed it down to this line: 

`mutate { gsub => ['message', "\n", "--NL--"] }`

following a `multiline`

I'm trying to create a reproducible test case, but it's definitely the above that if I remove it doesn't bomb out.

**Comment by suyograo** [comment]
@rmoff this is a duplicate of https://github.com/elastic/logstash/issues/3100. We have fixed this and will be releasing RC4

**Comment by rmoff** [comment]
Awesome, thanks. Sorry for the dup.

**Comment by suyograo** [comment]
no worries, thanks for trying RC3
