### PR TITLE
fix --config-test and add a couple of tests

### LINKED ISSUE #4933: --configtest not working on 2.3 (undefined method `config_valid?')
I'm getting the following error on 2 instances of logstash that were upgraded from 2.0 to 2.3, both are running ubuntu 12.04 amd64.

The error occurs when running `logstash -f /etc/logstash/conf.d --configtest`.
Since the new init script uses configtest when doing a restart, it means `/etc/init.d/logstash restart` cannot be used. 

```
An unexpected error occurred! {:error=>#<NoMethodError: undefined method `config_valid?' for LogStash::Pipeline:Class>, :class=>"NoMethodError", :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/agent.rb:169:in `execute'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/runner.rb:94:in `run'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/runner.rb:99:in `run'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/task.rb:24:in `initialize'"], :level=>:warn}
```

### PR DESCRIPTION
**Pull request by jsvd**
fixes #4933

### CODE REVIEW

File: logstash-core/lib/logstash/pipeline.rb [hunk 1]
```diff
@@ -56,6 +56,7 @@ def self.validate_config(config_str, settings = {})
     begin
       # There should be a better way to test this
       self.new(config_str, settings)
+      true
     rescue => e
       e.message
```
Comment (purbon) [inline logstash-core/lib/logstash/pipeline.rb]: please see: https://github.com/elastic/logstash/pull/4944#discussion_r58017201 on related change comment.

**Comment by purbon** [comment]
This is basically a port of https://github.com/elastic/logstash/pull/4944 to 5.0, in order not to repeat comments here, I would focus on getting first #4944 clear and then we can focus on special things here.

File: logstash-core/lib/logstash/pipeline.rb (hunk 1 above)
Comment (guyboertje) [inline logstash-core/lib/logstash/pipeline.rb]: Consider using nil instead of true so that the test on line 172 becomes so much more readable, nil being the absence of an error.  This is similar to the way Ruby returns nil on compact! in the absence of a change.
```ruby
if config_error
  @logger.fatal I18n.t("logstash.error", :error => config_error)
  return 1
else
  @logger.terminal "Configuration OK"
  return 0
end
```

Comment (purbon) [inline logstash-core/lib/logstash/pipeline.rb]: this is for sure a more clean solution, I try to keep comments on #4944 as basically is the same code ported here.

**Comment by jsvd** [comment]
another round of review welcome. essentially corrected the same things as in #4944

**Comment by guyboertje** [comment]
LGTM

**Comment by purbon** [comment]
LGTM
