### ISSUE TITLE
1.5.0 RC3 Ruby filter fails with undefined variable 'event'

### ISSUE THREAD

**Issue by ecweaver** [elastic/logstash#3118]
This ruby filter we've been running fine in 1.4.2...

filter {
  ruby {
    code => "begin; if !event['message'].nil?; event['message'] = event['message'].force_encoding('ASCII-8BIT').encode('UTF-8', :invalid => :replace, :undef => :replace, :replace => '?'); end; rescue; end;"
  }
}

Now fails on 1.5.0 RC3 with: "undefined local variable or method `event'." 

Is this  a regression, or has something else changed?

**Comment by jsvd** [comment]
@ecweaver it is indeed a regression, it is being addressed in #3110  (issue #3100 )

**Comment by ecweaver** [comment]
Thank you for the instant response!  I guess we can close this as a dupe. Awaiting those issues.

Thanks again.

**Comment by suyograo** [comment]
Same as #3110
