### ISSUE TITLE
--configtest not working on 2.3 (undefined method `config_valid?')

### ISSUE THREAD

**Issue by jraby** [elastic/logstash#4933]
I'm getting the following error on 2 instances of logstash that were upgraded from 2.0 to 2.3, both are running ubuntu 12.04 amd64.

The error occurs when running `logstash -f /etc/logstash/conf.d --configtest`.
Since the new init script uses configtest when doing a restart, it means `/etc/init.d/logstash restart` cannot be used. 

```
An unexpected error occurred! {:error=>#<NoMethodError: undefined method `config_valid?' for LogStash::Pipeline:Class>, :class=>"NoMethodError", :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/agent.rb:169:in `execute'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/runner.rb:94:in `run'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/runner.rb:99:in `run'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/task.rb:24:in `initialize'"], :level=>:warn}
```

**Comment by suyograo** [comment]
thanks, we'll check it out

**Comment by Jakauppila** [comment]
I'm getting the same error with 2.3.0 on Windows Server 2012 R2. It works fine with 2.2.2.

```
?[33mAn unexpected error occurred! {:error=>#<NoMethodError: undefined method `config_valid?' for LogStash::Pipeline:Class>, :class=>"NoMethodError", :backtrace=>["D:/Logstash/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/agent.rb:169:in `execute'", "D:/Logstash/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/runner.rb:94:in `run'", "org/jruby/RubyProc.java:281:in `call'", "D:/Logstash/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/runner.rb:99:in `run'", "org/jruby/RubyProc.java:281:in `call'", "D:/Logstash/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/task.rb:24:in `initialize'"], :level=>:warn}?[0m
```

**Comment by berglh** [comment]
My continuous integration testing is failing because of this, please fix :+1:

**Comment by Slach** [comment]
+1
i have same error
and currently my deployment scripts was broken

**Comment by sc0rp10** [comment]
+1
Ubuntu 14.04
service logstash configtest 

o\

**Comment by jsvd** [comment]
Unfortunately "-t/--config-test" had absolutely no tests, so we never realised it broke :-1: 

I've created a pr to fix the problem and a basic ok/nok test for the 2.3 branch. I'll create another against master in a few minutes.

Once the fix is merged we should expect a patch release shortly after as this is a huge bug..

**Comment by svenmueller** [comment]
when will this fix be available?

**Comment by colinsurprenant** [comment]
@svenmueller @alexClinebb @benlavender @Sakorah We just built a snapshot of 2.3.1 for sanity testing before doing a formal 2.3.1 release as soon as we green light this snapshot. Feel free to test that and let us know if that works for you.  +Standard disclaimer about a snapshot release.

**Comment by colinsurprenant** [comment]
forgot the links :grin: 
http://build-eu.elasticsearch.org.s3.amazonaws.com/logstash/2.3/nightly/JDK8/logstash_2.3.1~snapshot1-1_all.deb
http://build-eu.elasticsearch.org.s3.amazonaws.com/logstash/2.3/nightly/JDK8/logstash-2.3.1.snapshot1.tar.gz
http://build-eu.elasticsearch.org.s3.amazonaws.com/logstash/2.3/nightly/JDK8/logstash-2.3.1.snapshot1.zip
http://build-eu.elasticsearch.org.s3.amazonaws.com/logstash/2.3/nightly/JDK8/logstash-2.3.1~snapshot1-1.noarch.rpm

**Comment by colinsurprenant** [comment]
FYI 2.3.1 is released, https://www.elastic.co/blog/logstash-2.3.1-and-2.2.4-released

**Comment by jraby** [comment]
thx @colinsurprenant I'll test that.

**Comment by Sakorah** [comment]
2.3.1 worked for me on ubuntu14.04. I tried an upgrade from 2.3.0 (verified that configtest failed) to 2.3.1 and it worked.

**Comment by gaspaio** [comment]
Just stumbled into the error. It bothered me. Google it. Found this issue. Saw it was alreay fixed. Upgraded and everything is fine again.
God I love open-source :-). Many thanx to all.
