### ISSUE TITLE
undefined local variable or method `org' at event.rb:218

### ISSUE THREAD

**Issue by zde** [elastic/logstash#1276]
A missing require, perhaps?  This works with jruby, but fails on ruby1.9.1

``` ruby
Failed to flush outgoing items {:outgoing_count=>1, :exception=>#<NameError: undefined local variable or method `org' for 2014-04-16T10:35:35Z devbox %{message}:LogStash::Event>, :backtrace=>["/opt/logstash/lib/logstash/event.rb:218:in `block in sprintf'", "/opt/logstash/lib/logstash/event.rb:209:in `gsub'", "/opt/logstash/lib/logstash/event.rb:209:in `sprintf'", ...}
```
