### ISSUE TITLE
Logstash 7.9.1 template management fails to install index template

### ISSUE THREAD

**Issue by rkbennett** [elastic/logstash#12239]
When attempting to load index templates with logstash, it fails to install the index template

Version: docker.elastic.co/logstash/logstash:7.9.1

Expected result: index template is successfully loaded into elasticsearch

Actual result: receives the following error --  2020-09-12 17:22:00.050 [Ruby-0-Thread-18: /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.6.2-java/lib/logstash/outputs/elasticsearch/common.rb:40] elasticsearch - Failed to install template. {:message=>"undefined method `update' for nil:NilClass", :class=>"NoMethodError", :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.6.2-java/lib/logstash/outputs/elasticsearch/template_manager.rb:42:in `add_ilm_settings_to_template'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.6.2-java/lib/logstash/outputs/elasticsearch/template_manager.rb:15:in `install_template'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.6.2-java/lib/logstash/outputs/elasticsearch/common.rb:212:in `install_template'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.6.2-java/lib/logstash/outputs/elasticsearch/common.rb:49:in `block in setup_after_successful_connection'"]}

I had this working with the 7.6.0 image before, but for some reason it always throws this error now. I also had seen another issue where they were saying adding "settings": { } to the template fixed this issue in 7.0.1, but I'm already using that field as I'm also doing ILM on this index pattern.

**Comment by rkbennett** [comment]
Looking at the code in template_manager.rb, looks like it maps template to the root of the template object, but then deletes out the template key from the hash. It then attempts an update on template['settings'], which would actually be under template['template']['settings'], if template['template wasn't always deleted'], so when it attempts the template['settings'].update, it always fails

**Comment by rkbennett** [comment]
Realized this is more related to logstash-output-elasticsearch plugin, and submitted a pull request
