### ISSUE TITLE
Logstash 1.5 - event['@timestamp'] no longer supports the localtime() method

### ISSUE THREAD

**Issue by utilitynerd** [elastic/logstash#3278]
This filter block works fine in 1.4

 ruby {
            code  => "
                localtime = event['@timestamp'].localtime()
            "
}

but results in this error in 1.5:

{:timestamp=>"2015-05-18T17:21:15.919000-0700", :message=>"Exception in filterworker", "exception"=>#<NoMethodError: undefined method `localtime' for "2015-05-18T21:23:53.216Z":LogStash::Timestamp>, "backtrace"=>["(ruby filter code):2:in `register'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-ruby-0.1.5/lib/logstash/filters/ruby.rb:37:in `filter'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/filters/base.rb:162:in `multi_filter'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/filters/base.rb:159:in `multi_filter'", "(eval):673:in `cond_func_23'",

**Comment by jordansissel** [comment]
I'm not sure this should have worked in the first place. We'll want to firm up the expected interface on the time objects before we can fix this.

**Comment by colinsurprenant** [comment]
The `Timestamp` object in the Event has the `time` method to retrieve the underlying Ruby `Time` object. 

So for you to use `localtime` you should use:

```ruby
localtime = event.timestamp.time.localtime
```

**Comment by utilitynerd** [comment]
Thanks for the helpful comments.  Closing the ticket.
